services:
  db:
    image: postgres:16
    container_name: postgres_db_docker
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ecosystem
    ports:
      - "5434:5432"
    volumes:
      - postgres_final_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  app1:
    build: .
    container_name: app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecosystem
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SERVER_PORT=8081
      - SPRING_BATCH_JOB_ENABLED=false
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  app2:
    build: .
    container_name: app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecosystem
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SERVER_PORT=8081
      - SPRING_BATCH_JOB_ENABLED=false
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  apache-lb:
    image: httpd:latest
    container_name: apache_load_balancer
    ports:
      - '9999:80'
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - app-network

volumes:
  postgres_final_data:

networks:
  app-network:
    driver: bridge
