ServerRoot "/usr/local/apache2"
Listen 80

# 1. ����� ��������� �������� �������� �������� �������
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule status_module modules/mod_status.so
LoadModule watchdog_module modules/mod_watchdog.so

# 2. ����� ����� �������� ���������� ������� ������ ������� ��������
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so

User www-data
Group www-data


LogFormat "%h %l %u %t \"%r\" %>s %b \"%{BALANCER_WORKER_ROUTE}e\"" detailed_balancer
CustomLog /proc/self/fd/1 detailed_balancer
ErrorLog /proc/self/fd/2

<Directory />
    AllowOverride none
    Require all denied
</Directory>

<Location /balancer-manager>
    SetHandler balancer-manager
    Require all granted
</Location>

<Location /server-status>
    SetHandler server-status
    Require all granted
</Location>


<Proxy "balancer://mycluster">
    BalancerMember "http://app1:8081" route=app1
    BalancerMember "http://app2:8081" route=app2
    ProxySet lbmethod=byrequests
</Proxy>


ProxyPass /balancer-manager !
ProxyPass /server-status !
ProxyPass / balancer://mycluster/
ProxyPassReverse / balancer://mycluster/
