spring.application.name=ecosystem
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/parallel-ecommerce
spring.datasource.username=postgres
spring.datasource.password=m8498069
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
