spring.application.name=ecosystem
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/parallel-ecommerce
spring.datasource.username=postgres
spring.datasource.password=m8498069
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=20

app.seed.enabled=true
seed.users=5000
seed.products=1000
seed.orders=500000

batch.chunk.size=2000
batch.daily.cron=0 0 1 * * *

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
